export const GET_POKEMON_SUCCESS = 'GET_POKEMON_SUCCESS';
export const GET_POKEMONS_LIST_SUCCESS = 'GET_POKEMONS_LIST_SUCCESS';
export const GET_POKEMON_FAILED = 'GET_POKEMON_FAILED';
export const BEGIN_AJAX_CALL = 'BEGIN_AJAX_CALL';
export const AJAX_CALL_ERROR = 'AJAX_CALL_ERROR';
export const SET_CURRENT_POKEMON = 'SET_CURRENT_POKEMON';
